//! MCP `ServerHandler` implementation for Yggdrasil.
//!
//! `YggdrasilServer` wraps a `reqwest::Client` and `McpServerConfig` and
//! exposes the five core tools plus four optional HA tools and two resources
//! over the MCP protocol.
//!
//! When `McpServerConfig.ha` is `Some`, `HaClient` and `AutomationGenerator`
//! are constructed and stored.  All four HA tool methods check for `None` and
//! return an error message if HA is not configured.

use reqwest::Client;
use rmcp::{
    ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        AnnotateAble as _, Implementation, ListResourcesResult, PaginatedRequestParams,
        RawResource, ReadResourceRequestParams, ReadResourceResult, ServerCapabilities,
        ServerInfo,
    },
    tool, tool_handler, tool_router,
};
use std::sync::{Arc, OnceLock};
use std::time::Duration;
use uuid::Uuid;
use ygg_domain::config::McpServerConfig;
use ygg_ha::{AutomationGenerator, HaClient};

use crate::{
    resources::{RESOURCE_MEMORY_STATS, RESOURCE_MODELS, RESOURCE_SESSION_CONTEXT},
    tools::{
        GenerateParams, HaCallServiceParams, HaGenerateAutomationParams, HaGetStatesParams,
        HaListEntitiesParams, QueryMemoryParams, SearchCodeParams, StoreMemoryParams,
        generate, ha_call_service, ha_generate_automation, ha_get_states, ha_list_entities,
        list_models, query_memory, search_code, store_memory,
    },
};

/// The MCP server for Yggdrasil.
///
/// Holds an HTTP client (connection-pooled, clone-cheap), the service
/// configuration, and optional HA integration objects.  All tool calls are
/// forwarded over HTTP to Odin or Muninn.
#[derive(Clone)]
pub struct YggdrasilServer {
    client: Client,
    config: McpServerConfig,
    /// Optional HA REST client.  Present when `config.ha` is `Some`.
    ha_client: Option<HaClient>,
    /// Optional automation generator.  Present when `config.ha` is `Some`.
    generator: Option<AutomationGenerator>,
    tool_router: ToolRouter<Self>,
    /// Stable session ID for this MCP server instance.  Sent with generate
    /// requests so Odin can maintain a rolling context window across calls.
    session_id: String,
    /// Prefetched session context populated asynchronously at startup.
    /// Shared across all clones via Arc; OnceLock ensures one-time write.
    context_cache: Arc<OnceLock<String>>,
}

// ---------------------------------------------------------------------------
// Tool implementations via #[tool_router] macro
//
// NOTE: the #[tool_router] impl block MUST be annotated before from_config
// because from_config calls Self::tool_router() which is generated by the macro.
// ---------------------------------------------------------------------------

#[tool_router]
impl YggdrasilServer {
    // ── Core tools ──────────────────────────────────────────────────────────

    /// Search for code snippets in the indexed codebase using semantic search.
    ///
    /// Calls Muninn's /api/v1/search endpoint directly.
    #[tool(description = "Search for code snippets in the indexed codebase. \
        Provide a natural language or code query and get back ranked source \
        code results with file paths, language, and relevance scores.")]
    async fn search_code_tool(
        &self,
        Parameters(params): Parameters<SearchCodeParams>,
    ) -> String {
        let result = search_code(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Search engram memory for relevant past interactions.
    ///
    /// Calls Odin /api/v1/query, which proxies to Mimir.
    #[tool(description = "Search engram memory for relevant past interactions. \
        Returns cause/effect pairs with similarity scores.")]
    async fn query_memory_tool(
        &self,
        Parameters(params): Parameters<QueryMemoryParams>,
    ) -> String {
        let result = query_memory(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Store a new cause/effect memory engram.
    ///
    /// Calls Odin /api/v1/store, which proxies to Mimir.
    #[tool(description = "Store a new memory engram as a cause/effect pair. \
        Returns the UUID of the created engram.")]
    async fn store_memory_tool(
        &self,
        Parameters(params): Parameters<StoreMemoryParams>,
    ) -> String {
        let result = store_memory(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Generate a response from the LLM via Odin.
    ///
    /// Calls Odin /v1/chat/completions (non-streaming).
    #[tool(description = "Generate a response from the LLM via Odin. \
        Odin's semantic router selects the best backend model unless you \
        specify one explicitly. Returns the model's response text.")]
    async fn generate_tool(
        &self,
        Parameters(params): Parameters<GenerateParams>,
    ) -> String {
        let result = generate(&self.client, &self.config, params, Some(&self.session_id)).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// List all available LLM models registered with Odin.
    ///
    /// Calls Odin /v1/models.
    #[tool(description = "List all LLM models available through Odin, including \
        their backend assignments. Returns a markdown table.")]
    async fn list_models_tool(&self) -> String {
        let result = list_models(&self.client, &self.config).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── HA tools ─────────────────────────────────────────────────────────────

    /// Get all Home Assistant entity states.
    ///
    /// Returns a compact markdown summary grouped by domain (default) or the
    /// raw JSON array truncated to 50 entities.  Returns an error if HA is
    /// not configured.
    #[tool(description = "Get all Home Assistant entity states. \
        Returns a markdown summary grouped by domain (lights, switches, sensors, etc.). \
        Set summary=false for raw JSON (first 50 entities). \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_get_states_tool(
        &self,
        Parameters(params): Parameters<HaGetStatesParams>,
    ) -> String {
        let result = ha_get_states(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// List Home Assistant entities filtered by domain.
    ///
    /// Filters entity states by HA domain (e.g., "light", "switch", "sensor").
    /// Returns a markdown table with entity IDs, friendly names, states, and
    /// last-changed timestamps.  Returns an error if HA is not configured.
    #[tool(description = "List Home Assistant entities filtered by domain \
        (e.g., 'light', 'switch', 'sensor', 'climate', 'automation'). \
        Omit domain to list all entities. Returns a markdown table. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_list_entities_tool(
        &self,
        Parameters(params): Parameters<HaListEntitiesParams>,
    ) -> String {
        let result = ha_list_entities(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Call a Home Assistant service to control a device.
    ///
    /// Executes a real action on the HA instance (e.g., turn on a light, lock
    /// a door, set thermostat temperature).  Use with care — this performs
    /// actual device control.  Returns an error if HA is not configured.
    #[tool(description = "Call a Home Assistant service to control a device. \
        Provide domain (e.g., 'light'), service (e.g., 'turn_on'), and data \
        (e.g., {\"entity_id\": \"light.living_room\", \"brightness\": 200}). \
        WARNING: This performs real actions on your Home Assistant instance. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_call_service_tool(
        &self,
        Parameters(params): Parameters<HaCallServiceParams>,
    ) -> String {
        let result = ha_call_service(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Generate Home Assistant automation YAML from a natural-language description.
    ///
    /// Fetches current entity states and available services from HA, builds a
    /// structured context prompt, and sends it to Odin's reasoning model
    /// (qwen3:30b-a3b on Hugin).  Returns the generated YAML in a code fence.
    /// This call is slow (10-60s depending on LLM inference speed).
    /// Returns an error if HA is not configured.
    #[tool(description = "Generate Home Assistant automation YAML from a \
        natural-language description. \
        Example: 'Turn on living room lights at sunset'. \
        Uses the qwen3:30b-a3b reasoning model — expect 10-60s response time. \
        Always review the generated YAML before adding it to Home Assistant. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_generate_automation_tool(
        &self,
        Parameters(params): Parameters<HaGenerateAutomationParams>,
    ) -> String {
        let result =
            ha_generate_automation(self.ha_client.as_ref(), self.generator.as_ref(), params)
                .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }
}

impl YggdrasilServer {
    /// Construct the server from a config.
    ///
    /// If `config.ha` is `Some`, constructs `HaClient` and `AutomationGenerator`.
    /// The HA token is consumed from the config; it is never logged.
    ///
    /// A stable session UUID is generated for this instance and a background
    /// task is spawned to prefetch the active sprint context from Mimir.
    pub fn from_config(config: &McpServerConfig) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(config.timeout_secs))
            .build()
            .unwrap_or_else(|_| Client::new());

        let (ha_client, generator) = if let Some(ref ha_cfg) = config.ha {
            // Automation model: use qwen3:30b-a3b routed through Odin so that Odin's
            // backend semaphores and engram storage apply.
            let automation_gen = AutomationGenerator::new(&config.odin_url, "qwen3:30b-a3b");
            let ha = HaClient::from_config(ha_cfg);
            tracing::info!(ha_url = %ha_cfg.url, "HA integration enabled");
            (Some(ha), Some(automation_gen))
        } else {
            tracing::info!("HA integration disabled (no ha config)");
            (None, None)
        };

        let session_id = Uuid::new_v4().to_string();
        let context_cache: Arc<OnceLock<String>> = Arc::new(OnceLock::new());

        // Spawn a background task to prefetch the session context from memory.
        {
            let prefetch_client = client.clone();
            let prefetch_config = config.clone();
            let prefetch_cache = Arc::clone(&context_cache);
            let prefetch_query = config.prefetch_query.clone();
            tokio::spawn(async move {
                let params = QueryMemoryParams {
                    text: prefetch_query,
                    limit: Some(10),
                };
                let result = query_memory(&prefetch_client, &prefetch_config, params).await;
                let text = result
                    .content
                    .into_iter()
                    .next()
                    .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
                    .unwrap_or_default();
                // OnceLock::set fails silently if already set — that's fine.
                let _ = prefetch_cache.set(text);
                tracing::info!("Session context prefetch complete");
            });
        }

        Self {
            client,
            config: config.clone(),
            ha_client,
            generator,
            tool_router: Self::tool_router(),
            session_id,
            context_cache,
        }
    }
}

// ---------------------------------------------------------------------------
// ServerHandler implementation
// ---------------------------------------------------------------------------

#[tool_handler]
impl ServerHandler for YggdrasilServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new("yggdrasil", "0.1.0"))
    }

    fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> impl std::future::Future<
        Output = Result<ListResourcesResult, rmcp::ErrorData>,
    > + Send + '_ {
        async move {
            Ok(ListResourcesResult::with_all_items(vec![
                RawResource::new(RESOURCE_MODELS, "Available Models")
                    .with_description("Lists all LLM models available through Odin.")
                    .with_mime_type("text/plain")
                    .no_annotation(),
                RawResource::new(RESOURCE_MEMORY_STATS, "Memory Statistics")
                    .with_description("Engram count and tier statistics from Mimir.")
                    .with_mime_type("text/plain")
                    .no_annotation(),
                RawResource::new(RESOURCE_SESSION_CONTEXT, "Session Context")
                    .with_description("Prefetched active sprint context from Mimir memory.")
                    .with_mime_type("text/plain")
                    .no_annotation(),
            ]))
        }
    }

    fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> impl std::future::Future<
        Output = Result<ReadResourceResult, rmcp::ErrorData>,
    > + Send + '_ {
        let client = self.client.clone();
        let config = self.config.clone();
        let context_cache = Arc::clone(&self.context_cache);
        async move {
            match request.uri.as_str() {
                RESOURCE_MODELS => {
                    Ok(crate::resources::read_models_resource(&client, &config).await)
                }
                RESOURCE_MEMORY_STATS => {
                    Ok(crate::resources::read_memory_stats_resource(&client, &config).await)
                }
                RESOURCE_SESSION_CONTEXT => {
                    Ok(crate::resources::read_session_context_resource(&context_cache))
                }
                other => Err(rmcp::ErrorData::invalid_params(
                    format!("Unknown resource URI: {}", other),
                    None,
                )),
            }
        }
    }
}
