//! MCP `ServerHandler` implementation for Yggdrasil.
//!
//! `YggdrasilServer` wraps a `reqwest::Client` and `McpServerConfig` and
//! exposes the five core tools plus four optional HA tools and two resources
//! over the MCP protocol.
//!
//! When `McpServerConfig.ha` is `Some`, `HaClient` and `AutomationGenerator`
//! are constructed and stored.  All four HA tool methods check for `None` and
//! return an error message if HA is not configured.

use reqwest::Client;
use rmcp::{
    ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{
        AnnotateAble as _, Implementation, ListResourcesResult, PaginatedRequestParams,
        RawResource, ReadResourceRequestParams, ReadResourceResult, ServerCapabilities,
        ServerInfo,
    },
    tool, tool_handler, tool_router,
};
use std::sync::{Arc, OnceLock};
use std::time::Duration;
use uuid::Uuid;
use ygg_domain::config::McpServerConfig;
use ygg_ha::{AutomationGenerator, HaClient};

use crate::{
    resources::{RESOURCE_MEMORY_STATS, RESOURCE_MODELS, RESOURCE_SESSION_CONTEXT},
    tools::{
        AstAnalyzeParams, BuildCheckParams, ConfigSyncParams, ConfigVersionParams,
        ContextBridgeParams, ContextOffloadParams, DelegateParams, DiffReviewParams, GenerateParams,
        GetSprintHistoryParams, HaCallServiceParams, HaGenerateAutomationParams,
        HaGetStatesParams, HaListEntitiesParams, ImpactAnalysisParams, MemoryGraphParams,
        MemoryIntersectParams, MemoryTimelineParams, QueryMemoryParams, SearchCodeParams,
        ServiceHealthParams, StoreMemoryParams, TaskDelegateParams, TaskQueueParams,
        ast_analyze, build_check, config_sync, config_version, context_bridge,
        context_offload, diff_review, generate, get_sprint_history, ha_call_service,
        ha_generate_automation, ha_get_states, ha_list_entities, impact_analysis, list_models,
        memory_graph, memory_intersect, memory_timeline, query_memory, search_code,
        service_health, store_memory, task_delegate, task_queue,
    },
};

/// The MCP server for Yggdrasil.
///
/// Holds an HTTP client (connection-pooled, clone-cheap), the service
/// configuration, and optional HA integration objects.  All tool calls are
/// forwarded over HTTP to Odin or Muninn.
#[derive(Clone)]
pub struct YggdrasilServer {
    client: Client,
    config: McpServerConfig,
    /// Optional HA REST client.  Present when `config.ha` is `Some`.
    ha_client: Option<HaClient>,
    /// Optional automation generator.  Present when `config.ha` is `Some`.
    generator: Option<AutomationGenerator>,
    tool_router: ToolRouter<Self>,
    /// Stable session ID for this MCP server instance.  Sent with generate
    /// requests so Odin can maintain a rolling context window across calls.
    session_id: String,
    /// Prefetched session context populated asynchronously at startup.
    /// Shared across all clones via Arc; OnceLock ensures one-time write.
    context_cache: Arc<OnceLock<String>>,
}

// ---------------------------------------------------------------------------
// Tool implementations via #[tool_router] macro
//
// NOTE: the #[tool_router] impl block MUST be annotated before from_config
// because from_config calls Self::tool_router() which is generated by the macro.
// ---------------------------------------------------------------------------

#[tool_router]
impl YggdrasilServer {
    // ── Core tools ──────────────────────────────────────────────────────────

    /// Search for code snippets in the indexed codebase using semantic search.
    ///
    /// Calls Muninn's /api/v1/search endpoint directly.
    #[tool(description = "Search for code snippets in the indexed codebase. \
        Provide a natural language or code query and get back ranked source \
        code results with file paths, language, and relevance scores.")]
    async fn search_code_tool(
        &self,
        Parameters(params): Parameters<SearchCodeParams>,
    ) -> String {
        let result = search_code(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Search engram memory for relevant past interactions.
    ///
    /// Calls Odin /api/v1/query, which proxies to Mimir.
    #[tool(description = "Search engram memory for relevant past interactions. \
        Returns cause/effect pairs with similarity scores.")]
    async fn query_memory_tool(
        &self,
        Parameters(params): Parameters<QueryMemoryParams>,
    ) -> String {
        let result = query_memory(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Store a new cause/effect memory engram.
    ///
    /// Calls Odin /api/v1/store, which proxies to Mimir.
    #[tool(description = "Store a new memory engram as a cause/effect pair. Returns the UUID of the created engram. \
        To update an existing engram (bypassing the novelty gate), pass the engram UUID in the 'id' field. \
        To force-create a new engram even when a similar one exists, set force=true. \
        If a near-duplicate is detected, returns the existing memory for comparison — \
        you should then decide whether to update (pass id) or create new (pass force=true).")]
    async fn store_memory_tool(
        &self,
        Parameters(params): Parameters<StoreMemoryParams>,
    ) -> String {
        let result = store_memory(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Find engrams at the intersection, union, or difference of two concepts.
    ///
    /// Calls Odin /api/v1/sdr/operations, which proxies to Mimir.
    #[tool(description = "Find engrams at the intersection (AND), union (OR), or \
        symmetric difference (XOR) of two or more concepts using SDR set operations. \
        Returns matching engrams and Jaccard similarity between the concepts.")]
    async fn memory_intersect_tool(
        &self,
        Parameters(params): Parameters<MemoryIntersectParams>,
    ) -> String {
        let result = memory_intersect(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Generate a response from the LLM via Odin.
    ///
    /// Calls Odin /v1/chat/completions (non-streaming).
    #[tool(description = "Generate a response from the LLM via Odin. \
        Odin's semantic router selects the best backend model unless you \
        specify one explicitly. Returns the model's response text.")]
    async fn generate_tool(
        &self,
        Parameters(params): Parameters<GenerateParams>,
    ) -> String {
        let result = generate(
            &self.client,
            &self.config,
            params,
            Some(&self.session_id),
            self.config.project.as_deref(),
        )
        .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Retrieve recent sprint history from Yggdrasil engram memory.
    ///
    /// Queries Mimir for sprint-tagged engrams. Optionally filter by project.
    #[tool(description = "Retrieve recent sprint history from Yggdrasil engram memory. \
        Returns a markdown list of sprint summaries, newest first. \
        Optionally filter by project name (e.g. 'yggdrasil').")]
    async fn get_sprint_history_tool(
        &self,
        Parameters(params): Parameters<GetSprintHistoryParams>,
    ) -> String {
        let result = get_sprint_history(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// List all available LLM models registered with Odin.
    ///
    /// Calls Odin /v1/models.
    #[tool(description = "List all LLM models available through Odin, including \
        their backend assignments. Returns a markdown table.")]
    async fn list_models_tool(&self) -> String {
        let result = list_models(&self.client, &self.config).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── Foundation tools (Sprint 029 Phase E) ─────────────────────────────────

    /// Check health of all Yggdrasil services in a single call.
    ///
    /// Probes Odin, Mimir, Muninn, Ollama backends, and Qdrant in parallel.
    #[tool(description = "Check health of all Yggdrasil services (Odin, Mimir, Muninn, \
        Ollama backends, Qdrant) in a single call. Returns a status table with latency. \
        Use this to diagnose connectivity issues before other tool calls.")]
    async fn service_health_tool(
        &self,
        Parameters(params): Parameters<ServiceHealthParams>,
    ) -> String {
        let result = service_health(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Run cargo check/clippy on the workspace and return structured diagnostics.
    ///
    /// Requires workspace_path to be configured.
    #[tool(description = "Run cargo check, clippy, or test --no-run on the Yggdrasil \
        workspace. Returns structured diagnostics (errors, warnings) with file locations. \
        Use after code generation to verify compilation.")]
    async fn build_check_tool(
        &self,
        Parameters(params): Parameters<BuildCheckParams>,
    ) -> String {
        let result = build_check(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Query engrams with temporal and tag filters.
    ///
    /// Supports time ranges, tag filtering, and tier filtering.
    #[tool(description = "Query engram memory with temporal filters. Supports: \
        after/before (ISO 8601 datetime), tags (must have ALL listed), \
        tier (core/recall/archival), and optional semantic text search. \
        Example: memory_timeline_tool(after: '2026-03-01', tags: ['decision'])")]
    async fn memory_timeline_tool(
        &self,
        Parameters(params): Parameters<MemoryTimelineParams>,
    ) -> String {
        let result = memory_timeline(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Store, retrieve, or list offloaded context blocks.
    ///
    /// Use to offload large text (file contents, diffs, search results) to the
    /// server and reference by short handle, freeing up context window space.
    #[tool(description = "Offload large context to the server and reference by handle. \
        Actions: 'store' (content + optional label → handle), \
        'retrieve' (handle → content), 'list' (show all handles). \
        Use to free up context window space when working with large files or diffs.")]
    async fn context_offload_tool(
        &self,
        Parameters(params): Parameters<ContextOffloadParams>,
    ) -> String {
        let result = context_offload(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── Parent AI tools (Sprint 029 Phase B/C/D) ────────────────────────────

    /// Delegate code generation to a local LLM with full project context.
    ///
    /// Assembles context from code search + memory, then delegates to Ollama.
    #[tool(description = "Delegate code generation to a local LLM (free, fast). \
        Describe the task in natural language. Yggdrasil assembles context from \
        code search + memory + reference patterns, then generates code via Ollama. \
        Use for boilerplate, new handlers, tests, and repetitive code.")]
    async fn task_delegate_tool(
        &self,
        Parameters(params): Parameters<TaskDelegateParams>,
    ) -> String {
        let result = task_delegate(
            &self.client,
            &self.config,
            params,
            Some(&self.session_id),
            self.config.project.as_deref(),
        )
        .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Unified local AI delegation — replaces generate_tool + task_delegate_tool.
    ///
    /// Assembles context from memory (by UUID), code search, and inline files,
    /// loads agent-specific system prompts, and calls the local LLM.
    #[tool(description = "Delegate a task to the local LLM with full context assembly. \
        Specify agent_type ('executor', 'docs', 'qa', 'review', 'general') to load \
        the right system prompt. Provide memory_ids (engram UUIDs) and/or search_queries \
        for automatic context. Use file_context to pass pre-read file content. \
        Set structured_output=true to get parsed file blocks as JSON. \
        Use for boilerplate, docs, tests, code review, and any menial task.")]
    async fn delegate_tool(
        &self,
        Parameters(params): Parameters<DelegateParams>,
    ) -> String {
        let result = delegate(
            &self.client,
            &self.config,
            params,
            Some(&self.session_id),
            self.config.project.as_deref(),
        )
        .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Review a code diff or file content using local LLM with project memory.
    ///
    /// Fetches architectural decisions from memory to inform the review.
    #[tool(description = "Review code changes using local LLM with full project memory. \
        Pass a git diff or file content. The review checks for bugs, security issues, \
        architecture violations, and performance regressions. Reviews are stored as \
        engrams for future reference. Focus: 'security', 'performance', 'architecture', \
        'bugs', or 'all'.")]
    async fn diff_review_tool(
        &self,
        Parameters(params): Parameters<DiffReviewParams>,
    ) -> String {
        let result = diff_review(
            &self.client,
            &self.config,
            params,
            Some(&self.session_id),
            self.config.project.as_deref(),
        )
        .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Export or import context snapshots for cross-IDE continuity.
    ///
    /// Export context in one IDE, import in another to continue seamlessly.
    #[tool(description = "Export or import context snapshots for cross-IDE continuity. \
        Use 'export' to save current context (recent engrams, sprint info) with a label. \
        Use 'import' with the same label in another IDE to restore context. \
        Enables: Claude Code → export → Firebase Studio → import → continue.")]
    async fn context_bridge_tool(
        &self,
        Parameters(params): Parameters<ContextBridgeParams>,
    ) -> String {
        let result = context_bridge(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── AST analysis tools (Sprint 029 Phase 2) ──────────────────────────────

    /// Look up code symbols by name, type, language, or file path.
    ///
    /// Queries Huginn's tree-sitter indexed code_chunks table via Muninn.
    #[tool(description = "Look up code symbols (functions, structs, enums, traits, impls) \
        by exact name, chunk type, language, or file path. Uses Huginn's tree-sitter index. \
        At least one filter required. Returns a table of matching symbols with locations.")]
    async fn ast_analyze_tool(
        &self,
        Parameters(params): Parameters<AstAnalyzeParams>,
    ) -> String {
        let result = ast_analyze(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Find all references to a symbol across the indexed codebase.
    ///
    /// Uses BM25 text search over code chunks to find usages.
    #[tool(description = "Find all references to a symbol across the indexed codebase. \
        Uses BM25 full-text search on code content. Returns a table of chunks that \
        reference the symbol, ranked by relevance. Use before refactoring to understand \
        impact. Optionally exclude the definition chunk by passing its ID.")]
    async fn impact_analysis_tool(
        &self,
        Parameters(params): Parameters<ImpactAnalysisParams>,
    ) -> String {
        let result = impact_analysis(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── Task queue tool (Sprint 029 Phase 3) ──────────────────────────────────

    /// Persistent task queue for agent coordination.
    ///
    /// Push, pop, complete, cancel, or list tasks stored in PostgreSQL.
    #[tool(description = "Persistent task queue for agent coordination. \
        Actions: 'push' (create task with title, description, priority, tags), \
        'pop' (claim next pending task for an agent), \
        'complete' (mark task done with result), 'cancel' (cancel a task), \
        'list' (query tasks by status/project/agent). \
        Tasks survive server restarts. Use for multi-step workflows and delegation.")]
    async fn task_queue_tool(
        &self,
        Parameters(params): Parameters<TaskQueueParams>,
    ) -> String {
        let result = task_queue(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── Memory graph tool (Sprint 029 Phase 4) ────────────────────────────────

    /// Manage relationships between engrams in a directed graph.
    ///
    /// Create, remove, query, and traverse edges between memory engrams.
    #[tool(description = "Manage engram relationship graph. \
        Actions: 'link' (create edge between engrams with relation type and weight), \
        'unlink' (remove edge), 'neighbors' (get connected engrams by direction), \
        'traverse' (BFS walk up to N hops). \
        Relations: 'related_to', 'depends_on', 'supersedes', 'caused_by'. \
        Use to build knowledge graphs over memory for richer recall and reasoning.")]
    async fn memory_graph_tool(
        &self,
        Parameters(params): Parameters<MemoryGraphParams>,
    ) -> String {
        let result = memory_graph(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── HA tools ─────────────────────────────────────────────────────────────

    /// Get all Home Assistant entity states.
    ///
    /// Returns a compact markdown summary grouped by domain (default) or the
    /// raw JSON array truncated to 50 entities.  Returns an error if HA is
    /// not configured.
    #[tool(description = "Get all Home Assistant entity states. \
        Returns a markdown summary grouped by domain (lights, switches, sensors, etc.). \
        Set summary=false for raw JSON (first 50 entities). \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_get_states_tool(
        &self,
        Parameters(params): Parameters<HaGetStatesParams>,
    ) -> String {
        let result = ha_get_states(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// List Home Assistant entities filtered by domain.
    ///
    /// Filters entity states by HA domain (e.g., "light", "switch", "sensor").
    /// Returns a markdown table with entity IDs, friendly names, states, and
    /// last-changed timestamps.  Returns an error if HA is not configured.
    #[tool(description = "List Home Assistant entities filtered by domain \
        (e.g., 'light', 'switch', 'sensor', 'climate', 'automation'). \
        Omit domain to list all entities. Returns a markdown table. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_list_entities_tool(
        &self,
        Parameters(params): Parameters<HaListEntitiesParams>,
    ) -> String {
        let result = ha_list_entities(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Call a Home Assistant service to control a device.
    ///
    /// Executes a real action on the HA instance (e.g., turn on a light, lock
    /// a door, set thermostat temperature).  Use with care — this performs
    /// actual device control.  Returns an error if HA is not configured.
    #[tool(description = "Call a Home Assistant service to control a device. \
        Provide domain (e.g., 'light'), service (e.g., 'turn_on'), and data \
        (e.g., {\"entity_id\": \"light.living_room\", \"brightness\": 200}). \
        WARNING: This performs real actions on your Home Assistant instance. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_call_service_tool(
        &self,
        Parameters(params): Parameters<HaCallServiceParams>,
    ) -> String {
        let result = ha_call_service(self.ha_client.as_ref(), params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Generate Home Assistant automation YAML from a natural-language description.
    ///
    /// Fetches current entity states and available services from HA, builds a
    /// structured context prompt, and sends it to Odin's reasoning model
    /// (qwen3:30b-a3b on Hugin).  Returns the generated YAML in a code fence.
    /// This call is slow (10-60s depending on LLM inference speed).
    /// Returns an error if HA is not configured.
    #[tool(description = "Generate Home Assistant automation YAML from a \
        natural-language description. \
        Example: 'Turn on living room lights at sunset'. \
        Uses the qwen3:30b-a3b reasoning model — expect 10-60s response time. \
        Always review the generated YAML before adding it to Home Assistant. \
        Requires HA to be configured in the MCP server config.")]
    async fn ha_generate_automation_tool(
        &self,
        Parameters(params): Parameters<HaGenerateAutomationParams>,
    ) -> String {
        let result =
            ha_generate_automation(self.ha_client.as_ref(), self.generator.as_ref(), params)
                .await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    // ── Config sync tools ───────────────────────────────────────────────

    /// Check version info across server, client, and config components.
    #[tool(description = "Check version info for Yggdrasil server, client, and config. \
        Actions: 'info' (show all versions), 'check' (compare client vs latest), \
        'bump' (increment version — config auto-bumps on push).")]
    async fn config_version_tool(
        &self,
        Parameters(params): Parameters<ConfigVersionParams>,
    ) -> String {
        let result = config_version(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }

    /// Push, pull, or check status of synced config files.
    #[tool(description = "Manage cross-workstation config file sync. \
        Actions: 'push' (upload a config file — reads from disk if content is omitted), \
        'pull' (download and write a config file to disk with .bak backup), \
        'status' (show all synced configs with hashes and timestamps). \
        File types: 'global_settings', 'global_claude_md', 'project_settings', 'project_claude_md'.")]
    async fn config_sync_tool(
        &self,
        Parameters(params): Parameters<ConfigSyncParams>,
    ) -> String {
        let result = config_sync(&self.client, &self.config, params).await;
        result
            .content
            .into_iter()
            .next()
            .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
            .unwrap_or_default()
    }
}

impl YggdrasilServer {
    /// Construct the server from a config.
    ///
    /// If `config.ha` is `Some`, constructs `HaClient` and `AutomationGenerator`.
    /// The HA token is consumed from the config; it is never logged.
    ///
    /// A stable session UUID is generated for this instance and a background
    /// task is spawned to prefetch the active sprint context from Mimir.
    pub fn from_config(config: &McpServerConfig) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(config.timeout_secs))
            .build()
            .unwrap_or_else(|_| Client::new());

        let (ha_client, generator) = if let Some(ref ha_cfg) = config.ha {
            // Automation model: use qwen3:30b-a3b routed through Odin so that Odin's
            // backend semaphores and engram storage apply.
            let automation_gen = AutomationGenerator::new(&config.odin_url, "qwen3:30b-a3b");
            let ha = HaClient::from_config(ha_cfg);
            tracing::info!(ha_url = %ha_cfg.url, "HA integration enabled");
            (Some(ha), Some(automation_gen))
        } else {
            tracing::info!("HA integration disabled (no ha config)");
            (None, None)
        };

        let session_id = Uuid::new_v4().to_string();
        let context_cache: Arc<OnceLock<String>> = Arc::new(OnceLock::new());

        // Spawn a background task to prefetch the session context from memory.
        {
            let prefetch_client = client.clone();
            let prefetch_config = config.clone();
            let prefetch_cache = Arc::clone(&context_cache);
            let prefetch_query = config.prefetch_query.clone();
            tokio::spawn(async move {
                let params = QueryMemoryParams {
                    text: prefetch_query,
                    limit: Some(10),
                };
                let result = query_memory(&prefetch_client, &prefetch_config, params).await;
                let text = result
                    .content
                    .into_iter()
                    .next()
                    .and_then(|c| c.raw.as_text().map(|t| t.text.clone()))
                    .unwrap_or_default();
                // OnceLock::set fails silently if already set — that's fine.
                let _ = prefetch_cache.set(text);
                tracing::info!("Session context prefetch complete");
            });
        }

        Self {
            client,
            config: config.clone(),
            ha_client,
            generator,
            tool_router: Self::tool_router(),
            session_id,
            context_cache,
        }
    }
}

// ---------------------------------------------------------------------------
// ServerHandler implementation
// ---------------------------------------------------------------------------

#[tool_handler]
impl ServerHandler for YggdrasilServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new("yggdrasil", env!("CARGO_PKG_VERSION")))
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<ListResourcesResult, rmcp::ErrorData> {
        Ok(ListResourcesResult::with_all_items(vec![
            RawResource::new(RESOURCE_MODELS, "Available Models")
                .with_description("Lists all LLM models available through Odin.")
                .with_mime_type("text/plain")
                .no_annotation(),
            RawResource::new(RESOURCE_MEMORY_STATS, "Memory Statistics")
                .with_description("Engram count and tier statistics from Mimir.")
                .with_mime_type("text/plain")
                .no_annotation(),
            RawResource::new(RESOURCE_SESSION_CONTEXT, "Session Context")
                .with_description("Prefetched active sprint context from Mimir memory.")
                .with_mime_type("text/plain")
                .no_annotation(),
        ]))
    }

    fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> impl std::future::Future<
        Output = Result<ReadResourceResult, rmcp::ErrorData>,
    > + Send + '_ {
        let client = self.client.clone();
        let config = self.config.clone();
        let context_cache = Arc::clone(&self.context_cache);
        async move {
            match request.uri.as_str() {
                RESOURCE_MODELS => {
                    Ok(crate::resources::read_models_resource(&client, &config).await)
                }
                RESOURCE_MEMORY_STATS => {
                    Ok(crate::resources::read_memory_stats_resource(&client, &config).await)
                }
                RESOURCE_SESSION_CONTEXT => {
                    Ok(crate::resources::read_session_context_resource(&context_cache))
                }
                other => Err(rmcp::ErrorData::invalid_params(
                    format!("Unknown resource URI: {}", other),
                    None,
                )),
            }
        }
    }
}
